### PR TITLE
Refactor legacy 3.x functions

### PR DESCRIPTION
**Pull request by smortex**
Puppet 6 has removed support of extra methods for Puppet 3.x legacy
functions.  Switching to Puppet 4.x functions fix the issue, so switch
all functions to 4.x functions.

https://puppet.com/docs/puppet/6.4/functions_refactor_legacy.html#extra-methods

### CODE REVIEW

**Comment by smortex** [comment]
While I am here, it look like the `riemann::clj_map` and `riemann::clj_vec` functions are not used in the module (maybe you use them in your deployment?) and `riemann::puts` is only used in the smoke tests.

I wonder if they should be part of the module or not?

**Comment by faxm0dem** [comment]
I used to use `puts` for debugging purposes.
The other 2 are used in a seemingly usesless smoke test 🤔

thanks for spotting this - can you open an issue please?

**Comment by faxm0dem** [comment]
can you please add puppet 6 to the travis matrix so we can actually see if this change solves the intended target version ? ;-)

**Comment by smortex** [comment]
I attempted to update the build matrix (two latest commits in this PR).  Puppet 6 drop support of `puppet module build` and wants you to rely on the PDK to achieve this goal; but the PDK is not compatible with Puppet 4.

The test matrix is also quite large and more than 2 hours are needed to have feedback when pushing a change.  Maybe it can be shrieked?  Are you still using Puppet 4 or can we drop it from the CI?  Can we test against the latest version of each major release with the version of Ruby used in the puppet-agent bundle? How would you prefer us to manage this?

(Also I can remove these two last commits and we can handle this point in another PR if you think more thinking is required)

**Comment by faxm0dem** [comment]
* I'm more than happy to shorten the matrix. I'd love to have at least one common ruby for puppet 4 and 5, and maybe 2 rubies for puppet 6
* we're still using puppet 4 🙄
* pdk should work on puppet 4, or at least older versions...
* we don't *have* to test puppet 6, if that makes things easier for this PR

**Comment by smortex** [comment]
Thanks!  I fixed the last commits following your idea.

FYI, even the latest Puppet 4.x release does not work with the PDK, so I switched to attempt to build the module the legacy way and on failure attempt with the PDK.

Regarding version of Puppet & Ruby, i guess that we can use the exact versions you are using as a test environment for the build matrix (what are they?), and use the version of Ruby packaged in puppet-agent to run the tests on the latest version of Puppet 4, Puppet 5 and Puppet 6 (I already put them)?

**Comment by faxm0dem** [comment]
I like your brute-force solution to pdk vs. puppet 😂 much simpler than mine https://github.com/ccin2p3/puppet-patterndb/blob/puppet6/.travis.yml

**Comment by faxm0dem** [comment]
As for the versions, no idea ;) I'll add them later if in need

**Pull request merged**
