### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by smortex**
This PR adds the default configuration for this module to work out-of-the-box on FreeBSD.

### CODE REVIEW

**Comment by smortex** [comment]
pdk-1.5.0 seems to break the test suite.  Looks like they introduced a new way to target a particular Puppet version:
https://puppet.com/docs/pdk/1.x/new_features.html#validate-and-test-against-specific-puppet-versions-1-5-0

**Comment by smortex** [comment]
CI was fixed in #4.  I rebased the branch on top of master so that the PR tests pass.

**Comment by faxm0dem** [comment]
Could you please add the newly supported platform to `metadata.json` ?

**Comment by smortex** [comment]
Sure! Done!

**Comment by faxm0dem** [comment]
thanks !

**Pull request merged**
