### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by smortex**

### CODE REVIEW

**Review by faxm0dem — COMMENTED** [review]
Thanks !
What's `HISTORY.md` ?

**Comment by smortex** [comment]
> What's `HISTORY.md` ?

When generating the ChangeLog, if `github-changelog-generator` see a `HISTORY.md` file, it will only create ChangeLog entries for release newer that the first found in the `HISTORY.md` file, and append the raw `HISTORY.md`.

When a project had a `CHANGELOG.md` managed by hand, this help avoid loosing this content. See:
https://github.com/github-changelog-generator/github-changelog-generator/#migrating-from-a-manual-changelog

If our case:
* in the first commit I moved `CHANGELOG.md` to `HISTORY.md` and updated the release headers so that it match what `github-changelog-generator` expect;
* the content of the second commit was generated by running `bundle exec rake release:prepare` after bumping the version in `metadata.json`.

**Review by faxm0dem — APPROVED** [review]

**Comment by smortex** [comment]
Nice! I'll regenerate the changelog to update the release date and do the release!

**Comment by smortex** [comment]
Okay, I will just stop clicking on the "Retry" button each time a CentOS 8 workflow fail and assume they have some mirror issues that prevent the SUT to bootstrap in a timely fashion :unamused:.

**Pull request merged**
